on:
  push:
    branches: [towards_pages]

name: pkgdown

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    steps:
      - uses: actions/checkout@v4

      - name: Install pkgdown and package dependencies
        run: |
          BiocManager::install(
            pkgs = c(
              "pkgdown",
              BiocManager::dependencies(".", type = "all")
            ),
            ask = FALSE,
            update = FALSE
          )
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
